create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null,
  role text not null check (role in ('admin', 'generic')),
  password_hash text not null,
  password_salt text not null,
  password_iterations integer not null default 120000,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
before update on public.app_users
for each row
execute function public.set_updated_at();

alter table public.app_users enable row level security;

insert into public.app_users (
  username,
  display_name,
  role,
  password_hash,
  password_salt,
  password_iterations,
  is_active
)
values
  (
    'jeremias',
    'Jeremias',
    'admin',
    '038a8b092d5d91d2887570bfd07b552b13a6b24f6e0fc949ea9d26cf49b968b8',
    'f0ba1320bac8bc97402febecbb4fc30c',
    120000,
    true
  ),
  (
    'yeudy',
    'Yeudy',
    'admin',
    '01952bb6a342e3788dc7dd4cece77ee598990efba4abea70d21a5d03dbe92ce7',
    '01eee0263c914bd78bfe847f24dca214',
    120000,
    true
  )
on conflict (username) do update
set
  display_name = excluded.display_name,
  role = excluded.role,
  password_hash = excluded.password_hash,
  password_salt = excluded.password_salt,
  password_iterations = excluded.password_iterations,
  is_active = excluded.is_active;
