create table if not exists public.watchlist_scan_state (
  username text not null,
  coin text not null,
  timeframe text not null,
  last_scanned_at timestamptz,
  last_strategy_id text,
  last_strategy_version text,
  last_signal_created_at timestamptz,
  last_summary jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (username, coin, timeframe)
);

create table if not exists public.watchlist_scan_runs (
  id bigint generated by default as identity primary key,
  username text not null,
  active_list_name text,
  scan_source text not null default 'manual',
  coins_count integer not null default 0,
  frames_scanned integer not null default 0,
  signals_created integer not null default 0,
  signals_closed integer not null default 0,
  status text not null default 'ok',
  errors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);
